#include "operations.h"

Operation operations[0x100] = {
	[0x00] = {"NOP", NOP, OPERAND_NONE, OPERAND_NONE, ADDR_MODE_NONE, ADDR_MODE_NONE, 0, 0, 1, 4, },

	// 8 bit loads
	// 
	// LD A, R
	[0x7F] = {"LD A, A", LD, REGISTER, REGISTER, A, A, 0, 0, 1, 4},
	[0x78] = {"LD A, B", LD, REGISTER, REGISTER, A, B, 0, 0, 1, 4},
	[0x79] = {"LD A, C", LD, REGISTER, REGISTER, A, C, 0, 0, 1, 4},
	[0x7A] = {"LD A, D", LD, REGISTER, REGISTER, A, D, 0, 0, 1, 4},
	[0x7B] = {"LD A, E", LD, REGISTER, REGISTER, A, E, 0, 0, 1, 4},
	[0x7C] = {"LD A, H", LD, REGISTER, REGISTER, A, H, 0, 0, 1, 4},
	[0x7D] = {"LD A, L", LD, REGISTER, REGISTER, A, L, 0, 0, 1, 4},
	[0x7E] = {"LD A, (HL)", LD, REGISTER, ADDRESS_R16, A, HL, 0, 0, 1, 8},
	[0x1A] = {"LD A, (DE)", LD, REGISTER, ADDRESS_R16, A, DE, 0, 0, 1, 8},

	[0x47] = {"LD B, A", LD, REGISTER, REGISTER, B, A, 0, 0, 1, 4},
	[0x40] = {"LD A, B", LD, REGISTER, REGISTER, B, B, 0, 0, 1, 4},
	[0x41] = {"LD A, C", LD, REGISTER, REGISTER, B, C, 0, 0, 1, 4},
	[0x42] = {"LD A, D", LD, REGISTER, REGISTER, B, D, 0, 0, 1, 4},
	[0x43] = {"LD A, E", LD, REGISTER, REGISTER, B, E, 0, 0, 1, 4},
	[0x44] = {"LD A, H", LD, REGISTER, REGISTER, B, H, 0, 0, 1, 4},
	[0x45] = {"LD A, L", LD, REGISTER, REGISTER, B, L, 0, 0, 1, 4},
	[0x46] = {"LD A, (HL)", LD, REGISTER, ADDRESS_R16, B, HL, 0, 0, 1, 8},
	[0xF0] = {"LD A, (FF00 + u8)", LD, REGISTER, ADDRESS_R8_OFFSET, A, U8, 0, 0, 2, 12},

	[0x4F] = {"LD C, A", LD, REGISTER, REGISTER, C, A, 0, 0, 1, 4},
	[0x48] = {"LD C, B", LD, REGISTER, REGISTER, C, B, 0, 0, 1, 4},
	[0x49] = {"LD C, C", LD, REGISTER, REGISTER, C, C, 0, 0, 1, 4},
	[0x4A] = {"LD C, D", LD, REGISTER, REGISTER, C, D, 0, 0, 1, 4},
	[0x4B] = {"LD C, E", LD, REGISTER, REGISTER, C, E, 0, 0, 1, 4},
	[0x4C] = {"LD C, H", LD, REGISTER, REGISTER, C, H, 0, 0, 1, 4},
	[0x4D] = {"LD C, L", LD, REGISTER, REGISTER, C, L, 0, 0, 1, 4},
	[0x4E] = {"LD C, (HL)", LD, REGISTER, ADDRESS_R16, C, HL, 0, 0, 1, 8},

	[0x57] = {"LD D, A", LD, REGISTER, REGISTER, D, A, 0, 0, 1, 4},
	[0x50] = {"LD D, B", LD, REGISTER, REGISTER, D, B, 0, 0, 1, 4},
	[0x51] = {"LD D, C", LD, REGISTER, REGISTER, D, C, 0, 0, 1, 4},
	[0x52] = {"LD D, D", LD, REGISTER, REGISTER, D, D, 0, 0, 1, 4},
	[0x53] = {"LD D, E", LD, REGISTER, REGISTER, D, E, 0, 0, 1, 4},
	[0x54] = {"LD D, H", LD, REGISTER, REGISTER, D, H, 0, 0, 1, 4},
	[0x55] = {"LD D, L", LD, REGISTER, REGISTER, D, L, 0, 0, 1, 4},
	[0x56] = {"LD D, (HL)", LD, REGISTER, ADDRESS_R16, D, HL, 0, 0, 1, 8},

	[0x5F] = {"LD E, A", LD, REGISTER, REGISTER, E, A, 0, 0, 1, 4},
	[0x58] = {"LD E, B", LD, REGISTER, REGISTER, E, B, 0, 0, 1, 4},
	[0x59] = {"LD E, C", LD, REGISTER, REGISTER, E, C, 0, 0, 1, 4},
	[0x5A] = {"LD E, D", LD, REGISTER, REGISTER, E, D, 0, 0, 1, 4},
	[0x5B] = {"LD E, E", LD, REGISTER, REGISTER, E, E, 0, 0, 1, 4},
	[0x5C] = {"LD E, H", LD, REGISTER, REGISTER, E, H, 0, 0, 1, 4},
	[0x5D] = {"LD E, L", LD, REGISTER, REGISTER, E, L, 0, 0, 1, 4},
	[0x5E] = {"LD E, (HL)", LD, REGISTER, ADDRESS_R16, E, HL, 0, 0, 1, 8},

	[0x67] = {"LD H, A", LD, REGISTER, REGISTER, H, A, 0, 0, 1, 4},
	[0x60] = {"LD H, B", LD, REGISTER, REGISTER, H, B, 0, 0, 1, 4},
	[0x61] = {"LD H, C", LD, REGISTER, REGISTER, H, C, 0, 0, 1, 4},
	[0x62] = {"LD H, D", LD, REGISTER, REGISTER, H, D, 0, 0, 1, 4},
	[0x63] = {"LD H, E", LD, REGISTER, REGISTER, H, E, 0, 0, 1, 4},
	[0x64] = {"LD H, H", LD, REGISTER, REGISTER, H, H, 0, 0, 1, 4},
	[0x65] = {"LD H, L", LD, REGISTER, REGISTER, H, L, 0, 0, 1, 4},
	[0x66] = {"LD H, (HL)", LD, REGISTER, ADDRESS_R16, H, HL, 0, 0, 1, 8},

	[0x6F] = {"LD L, A", LD, REGISTER, REGISTER, L, A, 0, 0, 1, 4},
	[0x68] = {"LD L, B", LD, REGISTER, REGISTER, L, B, 0, 0, 1, 4},
	[0x69] = {"LD L, C", LD, REGISTER, REGISTER, L, C, 0, 0, 1, 4},
	[0x6A] = {"LD L, D", LD, REGISTER, REGISTER, L, D, 0, 0, 1, 4},
	[0x6B] = {"LD L, E", LD, REGISTER, REGISTER, L, E, 0, 0, 1, 4},
	[0x6C] = {"LD L, H", LD, REGISTER, REGISTER, L, H, 0, 0, 1, 4},
	[0x6D] = {"LD L, L", LD, REGISTER, REGISTER, L, L, 0, 0, 1, 4},
	[0x6E] = {"LD L, (HL)", LD, REGISTER, ADDRESS_R16, L, HL, 0, 0, 1, 8},

	[0xE2] = {"LD (FF00 + C), A", LD, ADDRESS_R8_OFFSET, REGISTER, C, A, 0, 0, 1, 8},
	// 
	// 
	// LD X, u8
	[0x3E] = {"LD A, u8", LD, REGISTER, MEM_READ, A, U8, 0, 0, 2, 8},
	[0x06] = {"LD B, u8", LD, REGISTER, MEM_READ, B, U8, 0, 0, 2, 8},
	[0x0E] = {"LD C, u8", LD, REGISTER, MEM_READ, C, U8, 0, 0, 2, 8},
	[0x16] = {"LD D, u8", LD, REGISTER, MEM_READ, D, U8, 0, 0, 2, 8},
	[0x1E] = {"LD E, u8", LD, REGISTER, MEM_READ, E, U8, 0, 0, 2, 8},
	[0x26] = {"LD H, u8", LD, REGISTER, MEM_READ, H, U8, 0, 0, 2, 8},
	[0x2E] = {"LD L, u8", LD, REGISTER, MEM_READ, L, U8, 0, 0, 2, 8},

	[0xE0] = {"LD (FF00 + u8), A", LD, MEM_READ_ADDR_OFFSET, REGISTER, U8, A, 0, 0, 2, 12},

	// LD (HL)

	[0x77] = {"LD (HL), A", LD, ADDRESS_R16, REGISTER, HL, A, 0, SECONDARY_NONE, 1, 8 },
	[0x32] = {"LD (HL-), A", LD, ADDRESS_R16, REGISTER, HL, A, 0, DEC_R_1, 1, 8 },
	[0x22] = {"LD (HL+), A", LD, ADDRESS_R16, REGISTER, HL, A, 0, INC_R_1, 1, 8 },

	// 16 bit loads

	[0x01] = {"LD BC, u16", LD, REGISTER16, MEM_READ16, BC, U16, 0, 0, 3, 12},
	[0x11] = {"LD DE, u16", LD, REGISTER16, MEM_READ16, DE, U16, 0, 0, 3, 12},

	// LD SP
	[0x31] = {"LD SP, u16", LD, REGISTER16, MEM_READ16, SP, U16, 0, 0, 3, 12, },
	[0xF9] = {"LD SP, HL", LD, REGISTER16, REGISTER16, SP, HL, 0, 0, 1, 8, },

	// LD HL
	[0x21] = {"LD HL, u16", LD, REGISTER16, MEM_READ16, HL, U16, 0, 0, 3, 12, },

	// ALU
	// INC r8
	[0x3C] = {"INC A", INC, REGISTER, ADDR_MODE_NONE, A, OPERAND_NONE, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, IGNORE}},
	[0x04] = {"INC B", INC, REGISTER, ADDR_MODE_NONE, B, OPERAND_NONE, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, IGNORE}},
	[0x0C] = {"INC C", INC, REGISTER, ADDR_MODE_NONE, C, OPERAND_NONE, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, IGNORE}},
	[0x14] = {"INC D", INC, REGISTER, ADDR_MODE_NONE, D, OPERAND_NONE, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, IGNORE}},
	[0x1C] = {"INC E", INC, REGISTER, ADDR_MODE_NONE, E, OPERAND_NONE, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, IGNORE}},
	[0x24] = {"INC H", INC, REGISTER, ADDR_MODE_NONE, H, OPERAND_NONE, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, IGNORE}},
	[0x2C] = {"INC L", INC, REGISTER, ADDR_MODE_NONE, L, OPERAND_NONE, 0, 0, 1, 4, {DEPENDENT, RESET, DEPENDENT, IGNORE}},

	// DEC R8
	[0x05] = {"DEC B", DEC, REGISTER, ADDR_MODE_NONE, B, OPERAND_NONE, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, IGNORE}},
	[0x0D] = {"DEC C", DEC, REGISTER, ADDR_MODE_NONE, C, OPERAND_NONE, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, IGNORE}},

	// SUB
	[0x90] = {"SUB A, B", SUB, REGISTER, REGISTER, A, B, 0, 0, 1, 4, {DEPENDENT, SET, DEPENDENT, DEPENDENT}},

	// CP
	[0xFE] = {"CP A, u8", CP, REGISTER, MEM_READ, A, U8, 0, 0, 2, 8, {DEPENDENT, SET, DEPENDENT, DEPENDENT}},

	//INC r16
	[0x13] = {"INC DE", INC, REGISTER16, ADDR_MODE_NONE, DE, OPERAND_NONE, 0, 0, 1, 8},
	[0x23] = {"INC HL", INC, REGISTER16, ADDR_MODE_NONE, HL, OPERAND_NONE, 0, 0, 1, 8},

	// DEC r16
	[0x1B] = {"INC DE", DEC, REGISTER16, ADDR_MODE_NONE, DE, OPERAND_NONE, 0, 0, 1, 8},


	[0x17] = {"RLA", RL, REGISTER, ADDR_MODE_NONE, A, OPERAND_NONE, 0, 0, 1, 4, {DEPENDENT, RESET, RESET, DEPENDENT}},


	// OR
	[0xB0] = { "OR A, B", OR, REGISTER, REGISTER, A, B, 0, 0, 1, 4, {DEPENDENT, RESET, RESET, RESET} },
	// XOR
	[0xAF] = {"XOR A, A", XOR, REGISTER, REGISTER, A, A, 0, 0, 1, 4, {DEPENDENT, RESET, RESET, RESET} },

	// PUSH
	[0xC5] = {"PUSH BC", PUSH, ADDR_MODE_NONE, REGISTER16, OPERAND_NONE, BC, 0, 0, 1, 16},

	// POP
	[0xC1] = {"POP BC", POP, REGISTER16, ADDR_MODE_NONE, BC, OPERAND_NONE, 0, 0, 1, 12},
	[0xD1] = {"POP DE", POP, REGISTER16, ADDR_MODE_NONE, DE, OPERAND_NONE, 0, 0, 1, 12},
	[0xE1] = {"POP HL", POP, REGISTER16, ADDR_MODE_NONE, HL, OPERAND_NONE, 0, 0, 1, 12},
	[0xF1] = {"POP AF", POP, REGISTER16, ADDR_MODE_NONE, AF, OPERAND_NONE, 0, 0, 1, 12},


	// JUMPS

	[0x18] = {"JR, i8", JP, ADDR_MODE_NONE, MEM_READ, OPERAND_NONE, I8, CONDITION_NONE, SECONDARY_NONE, 2, 12 } ,
	[0x20] = {"JR NZ, i8", JP, ADDR_MODE_NONE, MEM_READ, OPERAND_NONE, I8, CONDITION_NZ, ADD_T_4, 2, 8 } ,
	[0x28] = {"JR Z, i8", JP, ADDR_MODE_NONE, MEM_READ, OPERAND_NONE, I8, CONDITION_Z, ADD_T_4, 2, 8 } ,
	[0x38] = {"JR C, i8", JP, ADDR_MODE_NONE, MEM_READ, OPERAND_NONE, I8, CONDITION_C, ADD_T_4, 2, 8 } ,
	[0x30] = {"JR NC, i8", JP, ADDR_MODE_NONE, MEM_READ, OPERAND_NONE, I8, CONDITION_NC, ADD_T_4, 2, 8 } ,

	[0xC3] = {"JP u16", JP, ADDR_MODE_NONE, MEM_READ16, OPERAND_NONE, U16, CONDITION_NONE, SECONDARY_NONE, 3, 16 },
	[0xC2] = {"JP NZ u16", JP, ADDR_MODE_NONE, MEM_READ16, OPERAND_NONE, U16, CONDITION_NZ, ADD_T_4, 3, 12 },
	[0xCA] = {"JP Z u16", JP, ADDR_MODE_NONE, MEM_READ16, OPERAND_NONE, U16, CONDITION_Z, ADD_T_4, 3, 12 },
	[0xD2] = {"JP NC u16", JP, ADDR_MODE_NONE, MEM_READ16, OPERAND_NONE, U16, CONDITION_NC, ADD_T_4, 3, 12 },
	[0xDA] = {"JP C u16", JP, ADDR_MODE_NONE, MEM_READ16, OPERAND_NONE, U16, CONDITION_C, ADD_T_4, 3, 12 },
	[0xEA] = {"JP HL", JP, ADDR_MODE_NONE, REGISTER, OPERAND_NONE, HL, CONDITION_NONE, SECONDARY_NONE, 1, 4 },

	// CALLS
	[0xCD] = {"CALL u16", CALL, ADDR_MODE_NONE, MEM_READ16, OPERAND_NONE, U16, CONDITION_NONE, SECONDARY_NONE, 3, 24},

	// RET
	[0xC9] = {"RET", RET, ADDR_MODE_NONE, ADDR_MODE_NONE, OPERAND_NONE, OPERAND_NONE, CONDITION_NONE, SECONDARY_NONE, 1, 16},

	// MISC
	[0xCB] = {"PREFIX CB", CB, MEM_READ, ADDR_MODE_NONE, OPERAND_NONE, OPERAND_NONE, 0, 0, 1, 4},
};

Operation cb_operations[0x100] = {

	// BIT B, X // PUT THE BIT YOU ARE COMPARING INTO DEST AND REGISTER INTO SOURCE AND DONT ASK ANY QUESTIONS (if you think about it this actually makes more sense)	
	[0x47] = { "BIT 0, B", BIT, ADDR_MODE_NONE, REGISTER, 0, B, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x40] = { "BIT 0, C", BIT, ADDR_MODE_NONE, REGISTER, 0, C, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x41] = { "BIT 0, D", BIT, ADDR_MODE_NONE, REGISTER, 0, D, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x42] = { "BIT 0, E", BIT, ADDR_MODE_NONE, REGISTER, 0, E, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x43] = { "BIT 0, H", BIT, ADDR_MODE_NONE, REGISTER, 0, H, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x44] = { "BIT 0, L", BIT, ADDR_MODE_NONE, REGISTER, 0, L, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x45] = { "BIT 0, (HL)", BIT, ADDR_MODE_NONE, ADDRESS_R16, 0, HL, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },

	[0x4F] = { "BIT 1, A", BIT, ADDR_MODE_NONE, REGISTER, 1, A, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x48] = { "BIT 1, B", BIT, ADDR_MODE_NONE, REGISTER, 1, B, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x49] = { "BIT 1, C", BIT, ADDR_MODE_NONE, REGISTER, 1, C, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x4A] = { "BIT 1, D", BIT, ADDR_MODE_NONE, REGISTER, 1, D, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x4B] = { "BIT 1, E", BIT, ADDR_MODE_NONE, REGISTER, 1, E, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x4C] = { "BIT 1, H", BIT, ADDR_MODE_NONE, REGISTER, 1, H, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x4D] = { "BIT 1, L", BIT, ADDR_MODE_NONE, REGISTER, 1, L, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x4E] = { "BIT 1, (HL)", BIT, ADDR_MODE_NONE, ADDRESS_R16, 1, HL, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },

	[0x57] = { "BIT 2, A", BIT, ADDR_MODE_NONE, REGISTER, 2, A, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x50] = { "BIT 2, B", BIT, ADDR_MODE_NONE, REGISTER, 2, B, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x51] = { "BIT 2, C", BIT, ADDR_MODE_NONE, REGISTER, 2, C, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x52] = { "BIT 2, D", BIT, ADDR_MODE_NONE, REGISTER, 2, D, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x53] = { "BIT 2, E", BIT, ADDR_MODE_NONE, REGISTER, 2, E, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x54] = { "BIT 2, H", BIT, ADDR_MODE_NONE, REGISTER, 2, H, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x55] = { "BIT 2, L", BIT, ADDR_MODE_NONE, REGISTER, 2, L, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x56] = { "BIT 2, (HL)", BIT, ADDR_MODE_NONE, ADDRESS_R16, 2, HL, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },

	[0x5F] = { "BIT 3, A", BIT, ADDR_MODE_NONE, REGISTER, 3, A, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },[0x78] = { "BIT 7, B", BIT, ADDR_MODE_NONE, REGISTER, 7, B, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x58] = { "BIT 3, B", BIT, ADDR_MODE_NONE, REGISTER, 3, B, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x59] = { "BIT 3, C", BIT, ADDR_MODE_NONE, REGISTER, 3, C, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x5A] = { "BIT 3, D", BIT, ADDR_MODE_NONE, REGISTER, 3, D, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x5B] = { "BIT 3, E", BIT, ADDR_MODE_NONE, REGISTER, 3, E, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x5C] = { "BIT 3, H", BIT, ADDR_MODE_NONE, REGISTER, 3, H, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x5D] = { "BIT 3, L", BIT, ADDR_MODE_NONE, REGISTER, 3, L, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x5E] = { "BIT 3, (HL)", BIT, ADDR_MODE_NONE, ADDRESS_R16, 3, HL, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },

	[0x67] = { "BIT 4, B", BIT, ADDR_MODE_NONE, REGISTER, 4, B, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x60] = { "BIT 4, B", BIT, ADDR_MODE_NONE, REGISTER, 4, B, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x61] = { "BIT 4, C", BIT, ADDR_MODE_NONE, REGISTER, 4, C, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x62] = { "BIT 4, D", BIT, ADDR_MODE_NONE, REGISTER, 4, D, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x63] = { "BIT 4, E", BIT, ADDR_MODE_NONE, REGISTER, 4, E, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x64] = { "BIT 4, H", BIT, ADDR_MODE_NONE, REGISTER, 4, H, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x65] = { "BIT 4, L", BIT, ADDR_MODE_NONE, REGISTER, 4, L, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x66] = { "BIT 4, (HL)", BIT, ADDR_MODE_NONE, ADDRESS_R16, 4, HL, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },

	[0x6F] = { "BIT 5, A", BIT, ADDR_MODE_NONE, REGISTER, 5, A, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },[0x78] = { "BIT 7, B", BIT, ADDR_MODE_NONE, REGISTER, 7, B, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x68] = { "BIT 5, B", BIT, ADDR_MODE_NONE, REGISTER, 5, B, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x69] = { "BIT 5, C", BIT, ADDR_MODE_NONE, REGISTER, 5, C, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x6A] = { "BIT 5, D", BIT, ADDR_MODE_NONE, REGISTER, 5, D, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x6B] = { "BIT 5, E", BIT, ADDR_MODE_NONE, REGISTER, 5, E, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x6C] = { "BIT 5, H", BIT, ADDR_MODE_NONE, REGISTER, 5, H, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x6D] = { "BIT 5, L", BIT, ADDR_MODE_NONE, REGISTER, 5, L, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x6E] = { "BIT 5, (HL)", BIT, ADDR_MODE_NONE, ADDRESS_R16, 5, HL, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },

	[0x77] = { "BIT 6, B", BIT, ADDR_MODE_NONE, REGISTER, 6, B, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x70] = { "BIT 6, B", BIT, ADDR_MODE_NONE, REGISTER, 6, B, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x71] = { "BIT 6, C", BIT, ADDR_MODE_NONE, REGISTER, 6, C, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x72] = { "BIT 6, D", BIT, ADDR_MODE_NONE, REGISTER, 6, D, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x73] = { "BIT 6, E", BIT, ADDR_MODE_NONE, REGISTER, 6, E, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x74] = { "BIT 6, H", BIT, ADDR_MODE_NONE, REGISTER, 6, H, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x75] = { "BIT 6, L", BIT, ADDR_MODE_NONE, REGISTER, 6, L, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x76] = { "BIT 6, (HL)", BIT, ADDR_MODE_NONE, ADDRESS_R16, 6, HL, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },


	[0x7F] = { "BIT 7, A", BIT, ADDR_MODE_NONE, REGISTER, 7, A, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x78] = { "BIT 7, B", BIT, ADDR_MODE_NONE, REGISTER, 7, B, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x78] = { "BIT 7, B", BIT, ADDR_MODE_NONE, REGISTER, 7, B, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x79] = { "BIT 7, C", BIT, ADDR_MODE_NONE, REGISTER, 7, C, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x7A] = { "BIT 7, D", BIT, ADDR_MODE_NONE, REGISTER, 7, D, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x7B] = { "BIT 7, E", BIT, ADDR_MODE_NONE, REGISTER, 7, E, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x7C] = { "BIT 7, H", BIT, ADDR_MODE_NONE, REGISTER, 7, H, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x7D] = { "BIT 7, L", BIT, ADDR_MODE_NONE, REGISTER, 7, L, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },
	[0x7E] = { "BIT 7, (HL)", BIT, ADDR_MODE_NONE, ADDRESS_R16, 7, HL, 0, 0, 2, 8, {DEPENDENT, RESET, SET, IGNORE} },

	// RL
	[0x10] = {"RL B", RL, REGISTER, ADDR_MODE_NONE, B, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, DEPENDENT}},

	// SWAP
	[0x37] = {"SWAP A", SWAP, REGISTER, ADDR_MODE_NONE, A, OPERAND_NONE, 0, 0, 2, 8, {DEPENDENT, RESET, RESET, RESET}},

};


void print_operation(Operation op) {
	printf("0x%02X: \t%s\n", op.opcode, op.mnemonic);
}
